version: 2.1

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-29
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb # avoid weird output from Gradle

commands:
  prepare:
    description: "Prepares Android project-specific things"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Decode Android keystore
          command: echo $RELEASE_KEYSTORE_BASE64 | base64 -di | tee app/keystore.jks >/dev/null
      - run:
          name: Create keystore.properties
          command: 'printf "storePassword=`echo $RELEASE_KEYSTORE_PASSWORD`\nkeyPassword=`echo $RELEASE_KEY_PASSWORD`\nkeyAlias=BPInfo\nstoreFile=./keystore.jks\n" | tee keystore.properties >/dev/null '
      - run:
          name: Decode google-services.json
          command: echo $GOOGLE_SERVICES_JSON | base64 -di | tee app/google-services.json >/dev/null
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
          - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

jobs:
  test:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: Run Tests
          command: ./gradlew testLiveProdDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  lint:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: Run Tests
          command: ./gradlew lintLiveProdDebug --stacktrace
      - store_artifacts:
          path: app/build/reports
          destination: reports

  build:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: Build APKs and Bundles
          command: ./gradlew assembleLiveProdRelease assembleLiveStagingRelease bundleLiveProdRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/outputs/bundle
          destination: bundle

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - lint
      - test
      - build
